export {default as Login} from "./Login/Login"
export {default as Register} from './Register/Register'
export {default as AdminPanel} from './AdminPanel/AdminPanel';
export {default as Dashboard} from './Dashboard/Dashboard'
export {default as TuitionFeesPage} from './AdminPanel/TuitionFeesPage'
export {default as HostelFeesPage} from './AdminPanel/HostelFeesPage'
export {default as CollegeFeesPage} from './AdminPanel/CollegeFeesPage'
export {default as OtherFeesPage} from './AdminPanel/OtherFeesPage'
export {default as TransportFeesPage} from './AdminPanel/TransportFeesPage'
export {default as ForgotPassword} from './ForgotPassword/ForgotPassword'